<a href="https://colab.research.google.com/github/jaehyun-ko/COR1010/blob/main/hw9_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 구구단 구현

In [2]:
import numpy as np

In [9]:
nums=np.zeros([8*9,3])
for x in range(2,10):
  a=np.zeros((9,3))
  for y in range(0,9):
    a[y]=[x, y+1, x*(y+1)] #한번에 할당해도 됩니다!
  nums[(x-2)*9:(x-1)*9] = a #x-2는 0부터 시작하니까 한 단씩 채워지게 됩니다.
print(nums)

[[ 2.  1.  2.]
 [ 2.  2.  4.]
 [ 2.  3.  6.]
 [ 2.  4.  8.]
 [ 2.  5. 10.]
 [ 2.  6. 12.]
 [ 2.  7. 14.]
 [ 2.  8. 16.]
 [ 2.  9. 18.]
 [ 3.  1.  3.]
 [ 3.  2.  6.]
 [ 3.  3.  9.]
 [ 3.  4. 12.]
 [ 3.  5. 15.]
 [ 3.  6. 18.]
 [ 3.  7. 21.]
 [ 3.  8. 24.]
 [ 3.  9. 27.]
 [ 4.  1.  4.]
 [ 4.  2.  8.]
 [ 4.  3. 12.]
 [ 4.  4. 16.]
 [ 4.  5. 20.]
 [ 4.  6. 24.]
 [ 4.  7. 28.]
 [ 4.  8. 32.]
 [ 4.  9. 36.]
 [ 5.  1.  5.]
 [ 5.  2. 10.]
 [ 5.  3. 15.]
 [ 5.  4. 20.]
 [ 5.  5. 25.]
 [ 5.  6. 30.]
 [ 5.  7. 35.]
 [ 5.  8. 40.]
 [ 5.  9. 45.]
 [ 6.  1.  6.]
 [ 6.  2. 12.]
 [ 6.  3. 18.]
 [ 6.  4. 24.]
 [ 6.  5. 30.]
 [ 6.  6. 36.]
 [ 6.  7. 42.]
 [ 6.  8. 48.]
 [ 6.  9. 54.]
 [ 7.  1.  7.]
 [ 7.  2. 14.]
 [ 7.  3. 21.]
 [ 7.  4. 28.]
 [ 7.  5. 35.]
 [ 7.  6. 42.]
 [ 7.  7. 49.]
 [ 7.  8. 56.]
 [ 7.  9. 63.]
 [ 8.  1.  8.]
 [ 8.  2. 16.]
 [ 8.  3. 24.]
 [ 8.  4. 32.]
 [ 8.  5. 40.]
 [ 8.  6. 48.]
 [ 8.  7. 56.]
 [ 8.  8. 64.]
 [ 8.  9. 72.]
 [ 9.  1.  9.]
 [ 9.  2. 18.]
 [ 9.  3. 27.]
 [ 9.  4. 

또는 반복문 대신 파이썬의 장점인 슬라이싱을 써도 됩니다.

In [6]:
one_to_nine = np.array(range(1, 9+1))
print(one_to_nine)

[1 2 3 4 5 6 7 8 9]


In [8]:
nums=np.zeros([8*9,3])
for x in range(2,10):
  a = np.zeros((9,3))
  a[:,0] = x * np.ones(9)
  a[:,1] = one_to_nine
  a[:,2] = x * one_to_nine
  nums[(x-2)*9:(x-1)*9] = a #x-2는 0부터 시작하니까 한 단씩 채워지게 됩니다.

print(nums)

[[ 2.  1.  2.]
 [ 2.  2.  4.]
 [ 2.  3.  6.]
 [ 2.  4.  8.]
 [ 2.  5. 10.]
 [ 2.  6. 12.]
 [ 2.  7. 14.]
 [ 2.  8. 16.]
 [ 2.  9. 18.]
 [ 3.  1.  3.]
 [ 3.  2.  6.]
 [ 3.  3.  9.]
 [ 3.  4. 12.]
 [ 3.  5. 15.]
 [ 3.  6. 18.]
 [ 3.  7. 21.]
 [ 3.  8. 24.]
 [ 3.  9. 27.]
 [ 4.  1.  4.]
 [ 4.  2.  8.]
 [ 4.  3. 12.]
 [ 4.  4. 16.]
 [ 4.  5. 20.]
 [ 4.  6. 24.]
 [ 4.  7. 28.]
 [ 4.  8. 32.]
 [ 4.  9. 36.]
 [ 5.  1.  5.]
 [ 5.  2. 10.]
 [ 5.  3. 15.]
 [ 5.  4. 20.]
 [ 5.  5. 25.]
 [ 5.  6. 30.]
 [ 5.  7. 35.]
 [ 5.  8. 40.]
 [ 5.  9. 45.]
 [ 6.  1.  6.]
 [ 6.  2. 12.]
 [ 6.  3. 18.]
 [ 6.  4. 24.]
 [ 6.  5. 30.]
 [ 6.  6. 36.]
 [ 6.  7. 42.]
 [ 6.  8. 48.]
 [ 6.  9. 54.]
 [ 7.  1.  7.]
 [ 7.  2. 14.]
 [ 7.  3. 21.]
 [ 7.  4. 28.]
 [ 7.  5. 35.]
 [ 7.  6. 42.]
 [ 7.  7. 49.]
 [ 7.  8. 56.]
 [ 7.  9. 63.]
 [ 8.  1.  8.]
 [ 8.  2. 16.]
 [ 8.  3. 24.]
 [ 8.  4. 32.]
 [ 8.  5. 40.]
 [ 8.  6. 48.]
 [ 8.  7. 56.]
 [ 8.  8. 64.]
 [ 8.  9. 72.]
 [ 9.  1.  9.]
 [ 9.  2. 18.]
 [ 9.  3. 27.]
 [ 9.  4. 

[1 2 3 4 5 6 7 8 9]
