<a href="https://colab.research.google.com/github/jaehyun-ko/COR1010/blob/main/chapter9/hw9-1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import random
import numpy as np

r, c = 20, 2

scores = np.zeros([r,c])

scores.shape[0]
for score in scores: 
  score[0], score[1] = random.randint(1,40), random.randint(1,50)

print("All score list")
print(scores); print()
print("Mid score >= 25 & Final score >= 30 list")

good_table = scores[(scores[:, 0] >= 25)]
good_table = good_table[good_table[:, 1] >= 30]
print(good_table)

# 또는
print()
print("Mid score >= 25 & Final score >= 30 list")
good_table = scores[(scores[:, 0] >= 25) * (scores[:, 1] >= 30)]
print(good_table)


All score list
[[26. 13.]
 [27. 50.]
 [39. 35.]
 [24. 42.]
 [33. 47.]
 [15. 43.]
 [40. 12.]
 [15. 16.]
 [26. 41.]
 [36. 33.]
 [29.  6.]
 [28. 22.]
 [35. 23.]
 [38.  2.]
 [ 5. 12.]
 [23. 49.]
 [23.  6.]
 [19. 31.]
 [ 2. 50.]
 [32. 45.]]

Mid score >= 25 & Final score >= 30 list
[[27. 50.]
 [39. 35.]
 [33. 47.]
 [26. 41.]
 [36. 33.]
 [32. 45.]]

Mid score >= 25 & Final score >= 30 list
[[27. 50.]
 [39. 35.]
 [33. 47.]
 [26. 41.]
 [36. 33.]
 [32. 45.]]


All score list
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]

Mid score >= 25 & Final score >= 30 list
[]
